
import __ASTRO_IMAGE_IMPORT_1MpTut from "../../assets/houston.webp?astroContentImageFlag=&importer=src%2Fcontent%2Fdocs%2Faskama.mdx";
import __ASTRO_IMAGE_IMPORT_Z10nstG from "../../assets/BugWars.webp?astroContentImageFlag=&importer=src%2Fcontent%2Fdocs%2Fgame.mdx";
import __ASTRO_IMAGE_IMPORT_2j2sL3 from "../../assets/BugWars.webp?astroContentImageFlag=&importer=src%2Fcontent%2Fdocs%2Findex.mdx";
import __ASTRO_IMAGE_IMPORT_1yij9W from "../../../assets/BugWars.webp?astroContentImageFlag=&importer=src%2Fcontent%2Fdocs%2Fes%2Fgame.mdx";
import __ASTRO_IMAGE_IMPORT_1jw60y from "../../../assets/houston.webp?astroContentImageFlag=&importer=src%2Fcontent%2Fdocs%2Fes%2Findex.mdx";
import __ASTRO_IMAGE_IMPORT_29IN8q from "../../../assets/BugWars.webp?astroContentImageFlag=&importer=src%2Fcontent%2Fdocs%2Fja%2Fgame.mdx";
import __ASTRO_IMAGE_IMPORT_ZuNf2r from "../../../assets/houston.webp?astroContentImageFlag=&importer=src%2Fcontent%2Fdocs%2Fja%2Findex.mdx";
import __ASTRO_IMAGE_IMPORT_ZRMgER from "../../../assets/houston.webp?astroContentImageFlag=&importer=src%2Fcontent%2Fdocs%2Fko%2Findex.mdx";
import __ASTRO_IMAGE_IMPORT_Z188fCN from "../../../assets/BugWars.webp?astroContentImageFlag=&importer=src%2Fcontent%2Fdocs%2Fko%2Fgame.mdx";
export default new Map([["../../assets/houston.webp?astroContentImageFlag=&importer=src%2Fcontent%2Fdocs%2Faskama.mdx", __ASTRO_IMAGE_IMPORT_1MpTut], ["../../assets/BugWars.webp?astroContentImageFlag=&importer=src%2Fcontent%2Fdocs%2Fgame.mdx", __ASTRO_IMAGE_IMPORT_Z10nstG], ["../../assets/BugWars.webp?astroContentImageFlag=&importer=src%2Fcontent%2Fdocs%2Findex.mdx", __ASTRO_IMAGE_IMPORT_2j2sL3], ["../../../assets/BugWars.webp?astroContentImageFlag=&importer=src%2Fcontent%2Fdocs%2Fes%2Fgame.mdx", __ASTRO_IMAGE_IMPORT_1yij9W], ["../../../assets/houston.webp?astroContentImageFlag=&importer=src%2Fcontent%2Fdocs%2Fes%2Findex.mdx", __ASTRO_IMAGE_IMPORT_1jw60y], ["../../../assets/BugWars.webp?astroContentImageFlag=&importer=src%2Fcontent%2Fdocs%2Fja%2Fgame.mdx", __ASTRO_IMAGE_IMPORT_29IN8q], ["../../../assets/houston.webp?astroContentImageFlag=&importer=src%2Fcontent%2Fdocs%2Fja%2Findex.mdx", __ASTRO_IMAGE_IMPORT_ZuNf2r], ["../../../assets/houston.webp?astroContentImageFlag=&importer=src%2Fcontent%2Fdocs%2Fko%2Findex.mdx", __ASTRO_IMAGE_IMPORT_ZRMgER], ["../../../assets/BugWars.webp?astroContentImageFlag=&importer=src%2Fcontent%2Fdocs%2Fko%2Fgame.mdx", __ASTRO_IMAGE_IMPORT_Z188fCN]]);
		